# see https://docs.microsoft.com/en-us/azure/devops/pipelines/process/templates?view=azure-devops&viewFallbackFrom=vsts#passing-parameters
parameters:
  name: ''
  vmImage: ''
  displayName: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: ${{ parameters.vmImage }}

  strategy:
    maxParallel: 10
    matrix:
      Win32_Release:
        BuildPlatform: 'Win32'
        Configuration: 'Release'
      Win32_Debug:
        BuildPlatform: 'Win32'
        Configuration: 'Debug'
      Win64_Release:
        BuildPlatform: 'x64'
        Configuration: 'Release'
      Win64_Debug:
        BuildPlatform: 'x64'
        Configuration: 'Debug'

  steps:
  - script: echo $(BuildPlatform)
  - script: echo $(Configuration)
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
  - script: test.bat
